guery_manager/guery_manager/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from guery_manager.views import HomeView, DocsView
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
    url('', include('social_django.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^query/', include('queries.urls')),
    url(r'^docs/$', DocsView.as_view(), name='docs'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

guery_manager/queries/urls.py
from django.conf.urls import url
from queries.views import CreateNewQuery, UpdateQuerySchedule

app_name = 'queries'

urlpatterns = [
    url(r'^build/$', CreateNewQuery.as_view(), name='build'),
    url(r'^edit/(?P<pk>\d+)/$', UpdateQuerySchedule.as_view(), name='update'),
]

guery_manager/guery_manager/views.py
"""Query manager views."""

from django.views.generic import ListView, TemplateView
from queries.models import Queries


class HomeView(ListView):
    """Home view callable, for the home page."""

    template_name = 'guery_manager/manager.html'
    model = Queries

    def get_context_data(self):
        """Get queries from user."""
        context = super(HomeView, self).get_context_data()
        if self.request.user.is_anonymous():
            return
        else:
            context['queries'] = self.request.user.queries.all()
            return context


class DocsView(TemplateView):
    """Docs view callable."""

    template_name = 'guery_manager/docs.html'

guery_manager/guery_manager/templates/guery_manager/base.html
{% load staticfiles %}
{% csrf_token %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static '/css/vendor/bootstrap-datetimepicker.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/modules.css' %}">
    <!-- Font Awesome CDN -->
    <script src="https://use.fontawesome.com/457d33e4c6.js"></script>
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- Moment.js library -->
    <script scr="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <title></title>
</head>
<body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'home' %}">BigQuery Manager</a>
        </div>
        <ul class="nav navbar-nav">
          <li><a href="{% url 'queries:build' %}">Create a Query</a></li>
          <li><a href="{% url 'docs' %}">Docs</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'auth:logout' %}?next={{ request.path }}">Logout</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>

    {% block main %}
    {% endblock %}
</body>
</html>

guery_manager/guery_manager/templates/guery_manager/docs.html
{% extends 'guery_manager/base.html' %}
{% load staticfiles %}

{% block main %}
<section class="container-fluid main" id="about">
    <h1>BigQueryManager</h1>
    <p>This app will allow you to make queries to BigQuery. You will be able to store your data that you've quieried and you will be able to make a visual representation out of that data.</p>

    <h3>Using the application</h3>
    <h4>Requirements</h4>
    <ul>
        <li>a Google account</li>
        <li>a BigQuery account tied to your Google account</li>
        <li>a BigQuery project tied to your BigQuery account; you must have access to this project</li>
    </ul>

    <h3>Sign in</h3>
    <p>Authenticate using your Google account</p>

    <h4>Create a query</h4>
    <ul>
        <li>Navigate to the Create a Query link in the nav bar.</li>
        <li>Enter the input fields in the form; you'll need your BigQuery project id and a valid BigQuery query.</li>
        <li>Schedule your query to run on a schedule or once at a given time.</li>
    </ul>


    <h4>See your query</h4>
    <p>All scheduled queries are visible in the Query Manager, accessible from the home route or clicking on the BigQueryManager link in the nav bar.</p>

    <p>Clicking on a query will reveal any query instances, which represent every time a scheduled query ran. The query instance will contain links to the query results in BigQuery.</p>

    <h4>Update your query</h4>
    <p>If you'd like to change how often your query runs or stop it from running in the future, you can click on the schedule link on the query. You'll be directed to a form which will allow you to make those changes.</p>

    <h4>Logging out</h4>
    <div class="alert alert-warning" role="alert">
      <strong>Alert!</strong> If you log out, your scheduled queries will be canceled.
    </div>

    <h3>Code</h3>
    <p><a href="https://github.com/BigQueryManager/bigquerymgr" target="_blank">BigQueryManager on Github</a></p>

    <h3>Authors</h3>
    <ul>
        <li><a href="https://github.com/jjfeore" target="_blank">James Feore</a></li>
        <li><a href="https://github.com/ADL175" target="_blank">David Lim</a></li>
        <li><a href="https://github.com/morganelle" target="_blank">Morgan Nomura</a></li>
        <li><a href="https://github.com/Woojgh" target="_blank">James Salamonsen</a></li>
    </ul>
</section>

{% endblock %}

guery_manager/guery_manager/templates/guery_manager/manager.html
{% extends 'guery_manager/base.html' %}
{% load staticfiles %}

{% block main %}
{% if user.is_authenticated %}

    <section class="container-fluid main">
        <h1>Your queries</h1>
        <table class="table table-hover">
            <thead>
                <th>Query&nbsp;<a href="#" data-toggle="tooltip" title="QUERYGOESHERE"> <i class="fa fa-info-circle" aria-hidden="true"></i></a></th>
                <th><i class="fa fa-calendar" aria-hidden="true"></i>&nbsp;&nbsp;Schedule</th>
                <th><i class="fa fa-check" aria-hidden="true"></i>&nbsp;&nbsp;Last run</th>
            </thead>
            
            <tbody>
            {% for query in queries %}
                <tr data-toggle="collapse" data-target="#query{{ query.id }}-queries" class="clickable">
                    <td>{{ query.name }}</td>
                    <td><a href='{% url "queries:update" query.id %}'>{{ query.schedule }}</a></td>
                    <td>{{ query.last_run }}</td>
                </tr>
                {% if query.instances.all %}
                <tr>
                    <td colspan="3" class="query-instances">
                        <div id="query{{ query.id }}-queries" class="collapse">
                            <table class="table">
                                <thead>
                                    <th>Download</th>
                                    <th>Visualization</th>
                                    <th>Status</th>
                                    <th>Date</th>
                                </thead>
                                {% for query_instance in query.instances.all %}
                                <tr>
                                    <td>
                                        <a href="https://bigquery.cloud.google.com/results/{{ query_instance.root_url }}" target="_blank">CSV</a>
                                        <a href="https://bigquery.cloud.google.com/results/{{ query_instance.root_url }}" target="_blank">JSON</a>
                                    </td>
                                    <td>
                                        <a href="https://bigquery.cloud.google.com/results/{{ query_instance.visual_url }}" target="_blank">Visualization</a>
                                    </td>
                                    <td>
                                        <i class="fa fa-check" aria-hidden="true"></i>
                                    </td>
                                    <td>"{{ query_instance.status }}"</td>
                                </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </td>
                </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
    </section>

{% else %}
    <div class="container gimme-space">
        <div class="row">
            <div class="col-md-2 col-xs-2 col1 center-block center-this"> 
                <a id="login" href="{% url 'social:begin' 'google-oauth2' %}"><button type="button" class="btn btn-primary center-this"><strong>Login with Google</strong></button></a>
            </div>
        </div>
    </div>
{% endif %}

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static '/scripts/bqMgr.js' %}"></script>

{% endblock %}

guery_manager/guery_manager/templates/guery_manager/social_test.html
<!DOCTYPE html>
<html lang="en">
 <head>
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>{% block title %}Third-party Authentication Tutorial{% endblock %}</title>
 </head>
 <body>
   {% block main %}{% endblock %}
 </body>
</html>